version: '3.8'

services:
  my-app:
    build: .
    ports:
      - "3000:3000"
    command: npm run dev

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - my-app
