version: '3.7'
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2-arm64
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    restart: always

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:8.12.2-arm64
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/ssl/cert.crt:/usr/share/logstash/ssl/cert.crt
    depends_on:
      - elasticsearch
    ports:
      - "5001:5001"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.12.2-arm64
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    restart: always

  transcendence:
    container_name: transcendence
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - logstash
    environment:
      - LOGSTASH_HOST=logstash:5001
    ports:
      - "3000:3000"
