version: '3.7'
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2-arm64
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    restart: always
    networks:
      - lognet

  setupelastic:
    container_name: setupelastic
    image: curlimages/curl:latest
    depends_on:
      - elasticsearch
    restart: "no"
    entrypoint: [ "curl", "-X", "POST", "http://elasticsearch:9200/_security/user/kibana_system/_password", "-H", "Content-Type: application/json", "-d", "{\"password\": \"password\"}", "-u", "elastic:password" ]
    networks:
      - lognet

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:8.12.2-arm64
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch
    environment:
      - LS_JAVA_OPTS="-Xmx256m -Xms256m"
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "5001:5001"
    networks:
      - lognet

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.12.2-arm64
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./ssl:/usr/share/kibana/config/ssl
    depends_on:
      - elasticsearch
    environment:
      - KIBANA_USER=${KIBANA_USER}
      - KIBANA_PASSWORD=${KIBANA_PASSWORD}
      - KIBANA_ENCRYPTION_KEY=${KIBANA_ENCRYPTION_KEY}
    ports:
      - "5601:5601"
    restart: always
    networks:
      - lognet

  transcendence:
    container_name: transcendence
    build: .
    depends_on:
      - logstash
    environment:
      - LOGSTASH_HOST=logstash:5001
    ports:
      - "3000:3000"
    networks:
      - lognet

networks:
  lognet:
