version: '3.8'

services:
  postgres:
    build:
      context: Database/
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - transcendence
    restart: always

  nestjs:
    build:
      context: backend/
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - transcendence
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    restart: always

volumes:
  postgres_db:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./Database/data/postgres/"

networks:
  transcendence:
    driver: bridge
