# latest postgreSQL image
FROM postgres:latest

# environment variables 
ENV POSTGRES_USER=${POSTGRES_USER} \
	POSTGRES_PASSWORD=${POSTGRES_PASSWORD} \
	POSTGRES_DB=${POSTGRES_DB}

# standart port
EXPOSE 5432 
